### ISSUE TITLE
Datapackage name is not automatically set to pipeline name

### ISSUE THREAD

**Issue by cschloer** [frictionlessdata/datapackage-pipelines#176] opened 2020-01-24 12:34 UTC
On ubuntu python version 3.7.5 (and all other versions) the resulting datapackage has `_` as the name. I'm not sure if this is a consequence of moving over to dataflows, because dataflows uses the add_metadata processor to add name to the datapackage, but I think it's rather important that this feature exist in DPP without needing an extra processor. 
@roll @akariv

**Comment by roll** [comment] 2020-01-31 13:11
@cschloer 
Is it for every pipeline? I mean how can I reproduce it?

**Comment by cschloer** [comment] 2020-02-03 10:18
Yeah this happens for every pipeline created by dpp as far as I can tell.

**Comment by akariv** [comment] 2020-02-05 18:36
From the code it looks like this was never dpp's behaviour, and not a recent change...

1. I think it's better to start the pipeline with the explicit 'update_package' processor instead of magically settting the dataset name by some heuristic
2. This might be a breaking change to some users, expecting a certain dataset name

**Comment by cschloer** [comment] 2020-02-05 20:27
I think setting the datapackage.json name to the name of the pipeline-spec.yaml is not magic at all - it feels in fact like a bug that it is instead set to `_` (hence why we created this issue, thinking it was a bug). I see how adding an update package step seems like an easy workaround that can be applied every time, but that will quickly get annoying and feel rather chore-y for something that is supposed to be saving time. I could automatically insert an update_package step into the pipeline based on the pipeline-spec.yaml name but that feels more magic (automatically adding a new step) than it just already being called the pipeline name.

**Comment by roll** [comment] 2020-02-06 09:47
I think that not having `name` at all would be the purist option making a clear separation between pipeline/package (will not happen because it's def breaking).

But as it's anyway set to a value (an underscore) by default I think a pipeline title is a more reasonable default. I didn't see that DPP has this underscore as a part of API of docs so I don't think that changing it will be breaking.

**Comment by akariv** [comment] 2020-02-06 09:56
Unless I already have title to be something like 'My Lovely Dataset' which
is an invalid value as a dataset name, so would cause the pipeline to
fail...

**Comment by roll** [comment] 2020-02-06 10:18
Good point. We can slugify, of course. But yea I don't know whether this change is worth it

**Comment by cschloer** [comment] 2020-02-06 13:19
I've been using a regular expression to remove invalid characters, set
everything to lowercase, and replace spaces with underscores. Though I
agree that adds a level of "magic" to the equation.

**Comment by roll** [comment] 2020-03-02 17:15
@akariv 
@cschloer 
Closing it and #178, for now.

We had a discussion and as a summary:
- this feature might be still tempting 
- we understand that it's a breaking change and a pipeline name / dp name are different domains
- it's possible and even may be useful to have a visible/hidden processor in the client UI code for update a package name
- so, for now, we're going to try implementing it in the client's code

**Closed by roll** 2020-03-02 17:15 UTC
